# *********************************************************
# MT Workflow configuration file 
# *********************************************************

# =========================================================
# Input/Output files
# =========================================================

# Path to the file defining the eq catalog.
eq_catalog_file: tests/data/completeness_input_test.csv 

# Path to the file defining the transformed 
# eq catalog after the preprocessing jobs.
# If not defined no file will be written.
pprocessing_result_file: tests/data/preprocessed_catalogue.csv

# Path to the file defining the computed
# completeness table after preprocessing jobs
completeness_table_file: tests/data/completeness_table.csv

# Path to the file defining the source model.
source_model_file: tests/data/area_source_model_processing.xml

# Path to the file defining the results 
# of computation.
result_file: tests/data/output.xml

# Boolean flag to declare
# if processing jobs are needed.
apply_processing_jobs: yes

# =========================================================
# List of preprocessing jobs
# =========================================================


# Choose one algorithm per preprocessing job,
# algorithms will be executed in the specified
# order.
preprocessing_jobs:
- GardnerKnopoff
- Stepp


# =========================================================
# List of processing jobs
# =========================================================


# Choose one algorithm per preprocessing job,
# algorithms will be executed in the specified
# order.
processing_jobs:
- Recurrence
- MaximumMagnitude

# =========================================================
# Preprocessing jobs in detail
# =========================================================

# Declustering jobs

GardnerKnopoff: {
  # Possible values: `GardnerKnopoff`, `Uhrhammer`, `Gruenthal`.
  # `GardnerKnopoff` is the default choice.
  time_dist_windows: GardnerKnopoff,

  # float >= 0 proportion of aftershock time windows 
  # to use to search for foreshock.
  foreshock_time_window: 0
}

Afteran: {
    # Possible values: GardnerKnopoff, Uhrhammer, Gruenthal.
    time_dist_windows: Uhrhammer,
    
    # float >= 0 
    # Length (in days) of moving time window
    time_window: 60.0
}

Reasenberg: {
    # Interaction radius for dependent events (km)
    # float >= 0
    rfact: 10.0,

    # Effective lower magnitude cut-off for the catalogue
    # float 
    xmeff: 1.5,

    # Factor to raise the lower magnitude within clusters
    # float >= 0
    xk: 0.5,

    # Minimum look-ahead time for non clustered events
    # float >= 0
    taumin: 1.0,

    # Maximum look ahead time for clustered events
    # float >= 0
    taumax: 10.0,

    # Confidence Level for the next event in the sequence
    # float >= 0 in range 0.0 <= plev <= 1.0
    plev: 0.95
}

# Completeness jobs

Stepp: {
  # Time Window of each step (in years)
  time_window: 5,

  # Magnitude window of each step (in Mw units)
  magnitude_windows: 0.2,
  
  # Sensitivity parameter (see documentation)
  sensitivity: 0.1,
  
  # Increment Lock (fixes that the completeness magnitude
  # will always increase further back in time)
  increment_lock: True 
} 


# =========================================================
# Processing jobs in detail
# =========================================================

# Recurrence job

Recurrence: {
    # Width of magnitude window positive float
    magnitude_window: 0.2,
    
    # Choose one among `Weichert` or `MLE`
    recurrence_algorithm: Weichert,

    # A float
    reference_magnitude: 1.1,

    # Greater than zero (float), used only with Wiechart
    time_window: 0.2
}

MaximumMagnitude: {
    
    # Chosose one among `Kijko_Npg`, `Cumulative_Moment`.
    # default choice: Cumulative_Moment,
    maxim_mag_algorithm: Kijko_Npg,

    # float > 0, default value 1.0E-5
    iteration_tolerance: ,

    # int > 0, default value 1000
    maximum_iterations: ,

    # float > 0
    # better to take from catalogue
    max_observed_mag: ,
    
    # float > 0
    max_observed_mag_unc: ,

    # neq
    neq: ,

    # Used in Kijko_Npg
    # int > 0 default value 51
    number_samples: ,

    # Used in Cumulative_Moment
    # int > 0 default value 100
    number_bootstraps: 
}
